bridges = []

[[instances]]
name = "Testing DNA"
id = "__passthrough"
dna_hash = "QmcjoGNWszyb9pbZEXkj9Ujk8vpycRL47VqTSjfvrU4JVs"
uri = "https://github.com/holochain/passthrough-dna/releases/download/v0.0.8/passthrough-dna.dna.json"

[[UIs]]
name = "Testing UI"
id = "__testing-ui"
ui_bundle_hash = "Qm34abcde"
uri = "https://github.com/holochain/passthrough-dna/releases/download/v0.0.8/ui.zip"

[[UIs.instance_references]]
ui_handle = "test-instance"
instance_id = "__passthrough"
