bridges = []

[[instances]]
name = "Testing DNA"
id = "__passthrough"
dna_hash = "QmXA95Z3A1efoQX8mixJYeJs9GUn25tHYBhZs7JboQbz1W"
uri = "https://github.com/holochain/passthrough-dna/releases/download/v0.0.1/passthrough-dna.dna.json"

[[UIs]]
name = "Testing UI"
id = "__testing-ui"
ui_bundle_hash = "Qm34abcde"
uri = "https://github.com/holochain/passthrough-dna/releases/download/v0.0.1/ui.zip"

[[UIs.instance_references]]
ui_handle = "test-instance"
instance_id = "__passthrough"
