bridges = []
persistence_dir = ''
ui_bundles = []
ui_interfaces = []

[[agents]]
id = 'hc-run-agent'
keystore_file = 'testAgent1'
name = 'testAgent1'
public_address = 'HcSCiT653tXzNP5hs5JOWPJMURc4pukquwpchbUQU4wuxdesZiVdHtG36Ct3npa'
test_agent = true

[[dnas]]
file = '../../dist/passthrough-dna.dna.json'
hash = 'QmUf4dg5smKd1EZxQ9o4r6HvTYmbTepHXN7n1XHAJGiRJ2'
id = 'hc-run-dna'

[[instances]]
agent = 'hc-run-agent'
dna = 'hc-run-dna'
id = 'test-instance'

[instances.storage]
path = '../var/agent1db'
type = 'lmdb'

[[interfaces]]
admin = true
id = 'websocket-interface'

[[interfaces.instances]]
id = 'test-instance'

[interfaces.driver]
port = 8888
type = 'websocket'

[logger]
state_dump = false
type = 'debug'

[logger.rules]
rules = []

[network]
sim2h_url = 'ws://sim2h-test.holo.host:9001'
type = 'sim2h'

[passphrase_service]
type = 'cmd'

[signals]
consistency = false
trace = false
